permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
safe: true
lsi: false
pygments: false

title : MMDAI Project Portal2
tagline:
author :
  name : hkrn
  github : hkrn
  twitter : shimacpyon

production_url : http://hkrn.github.com/MMDAI
JB :
  version : 0.2.13
  ASSET_PATH : false
  BASE_PATH: /
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-18872148-7'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
  sharing :
    provider : false

